"""LLM abstraction.

Four task-focused methods, kept narrow so backends can specialise.
The chapter-analysis flow (see ``BookService.generate_chapter_meta``) is:

  1. ``classify_chapter_characters`` — list non-narrator characters in
     this chapter, classified as new / evolved.
  2. (Code, not LLM) gather cross-chapter introduction context for each
     new character — first 3 line-occurrences in the book, ±3 lines.
  3. ``profile_new_characters`` — generate profile for each new
     character using the gathered context.
  4. ``segment_chapter`` — split the chapter into single-speaker
     reading segments. Speakers should now resolve to known characters
     (since steps 1-3 registered them); any leftover unknown name is
     mapped to the narrator by reconciliation.

Splitting profile work from segmentation is a correctness fix for
non-linear reading: a reader who jumps to chapter 50 may land on a
character whose introduction lives in chapter 5. Step 2 ensures
profile generation always sees the original introduction text
regardless of read order.
"""
from __future__ import annotations

from typing import Protocol

from ..core.models import (
    AnalyzedSentence,
    ChapterDetection,
    Character,
    ClassifiedCharacters,
)


class LLMClient(Protocol):
    def detect_chapters(
        self,
        opening_text: str,
        *,
        known_titles: list[str] | None = None,
    ) -> ChapterDetection:
        """Infer chapter structure from a batch of book-opening lines (§2.4.1).

        Each call sees one 200-line batch. The model decides whether a
        table-of-contents block is present and returns either:
        - TOC mode: ``chapter_titles`` extracted from this batch's window
          plus ``toc_complete`` signalling whether the TOC has ended.
        - Pattern mode: ``first_chapter_title`` + ``chapter_pattern``
          (a Python regex the caller compiles and scans the full text with).

        Implementations SHOULD return an empty ``ChapterDetection`` on
        parse failure so callers can fall back to a single chapter.
        """

    def classify_chapter_characters(
        self,
        chapter_text: str,
        known_characters: list[Character],
    ) -> ClassifiedCharacters:
        """Identify all non-narrator characters this chapter touches and
        classify each as new / evolved / stable.

        - ``new_names``: names not in ``known_characters``. Only the
          name is emitted — full profile is generated by a follow-up
          ``profile_new_characters`` call with cross-chapter context.
        - ``evolved``: known characters whose profile changed enough
          this chapter (age range crossed, identity shifted, etc.).
          Full new profile attached.

        Stable known characters are intentionally absent. Returns an
        empty ``ClassifiedCharacters`` on parse failure.
        """

    def profile_new_characters(
        self,
        name_to_contexts: dict[str, list[str]],
        known_characters: list[Character],
    ) -> list[Character]:
        """Generate full profiles for newly-identified characters using
        cross-chapter introduction context windows.

        ``name_to_contexts`` maps each new character's name to up to N
        formatted context windows (each window = the line containing
        the name plus a few lines on either side, prefixed with chapter
        / line metadata). Empty context lists are allowed (the LLM
        will profile from name alone — graceful degradation).

        ``known_characters`` is included so the LLM can avoid attribute
        overlap with existing voices.

        Returns one ``Character`` per new name. ``id`` is a placeholder
        (0); the BookService merge step assigns real ids.
        """

    def segment_chapter(
        self,
        chapter_text: str,
        known_characters: list[Character],
    ) -> list[AnalyzedSentence]:
        """Split a chapter into single-speaker **reading segments**,
        attribute each segment to a speaker, and classify its tone.

        ``known_characters`` should be the up-to-date roster (after the
        Phase A character analysis has registered any new names) so the
        LLM uses canonical names. Any unknown speaker name in the
        result is mapped to the narrator by reconciliation downstream.

        Returns raw ``AnalyzedSentence`` objects (verbatim text +
        free-form speaker name + tone). The caller derives positions
        via ``core.nlp.sentences.locate_sentences``.

        Returns an empty list on parse failure.
        """
