"""Pydantic models for meta.json, chapter metadata and API payloads."""
from __future__ import annotations

from pydantic import BaseModel, Field

from .enums import Age, BookStatus, Gender, Personality, Tone


class ChapterEntry(BaseModel):
    id: int
    title: str
    text_file: str
    meta_file: str


class Character(BaseModel):
    id: int
    name: str
    # Short identity description (e.g. "少年弟子，主角，手持玄重尺"). LLM
    # uses it to recognise aliases ("萧家少主" = "萧炎") in subsequent
    # chapters. Empty when the LLM didn't supply one (rare).
    identity: str = ""
    gender: Gender = Gender.NEUTRAL
    age: Age = Age.ADULT
    personality: list[Personality] = Field(default_factory=list)


class BookMeta(BaseModel):
    """Book-level static info written once at import.

    Generated by ``ingest_txt`` / ``ingest_epub`` and **never mutated**
    afterwards (apart from the one-shot ``status: processing → ready``
    flip when ``analyze_book`` runs). Characters live in a separate
    ``characters.json`` (server-only) and as per-chapter snapshots inside
    each ``ChapterMeta``; see docs/technical-plan.md §2.3.
    """

    version: int = 1
    book_id: str
    title: str
    author: str = ""
    cover: str | None = None
    summary: str = ""
    chapters: list[ChapterEntry] = Field(default_factory=list)
    # Server-only fields (App ignores unknown fields anyway).
    status: BookStatus = BookStatus.PROCESSING
    source_filename: str | None = None


class Sentence(BaseModel):
    start_line: int
    start_col: int
    end_line: int
    end_col: int
    character_id: int = 0
    tone: Tone = Tone.NEUTRAL
    # Server-only debug field — the verbatim sentence text after
    # ``locate_sentences`` resolves the position. Lets a developer eyeball
    # `chapters/N.json` and immediately spot mis-segmentation without
    # cross-referencing the source text. **Stripped from API responses**
    # by ``chapter_meta_stream`` so the App still gets the lean
    # positions-only payload.
    text: str | None = None


class ChapterMeta(BaseModel):
    """Per-chapter metadata returned to the App.

    Contains the chapter's sentences AND a **snapshot** of every
    character that speaks in this chapter, with their full profile as
    of when this chapter was analysed. The App uses ``characters`` to
    pick TTS voices — no need to consult any global character table.

    Snapshot semantics: re-analysing a later chapter where 萧炎's
    profile evolves from teen → youth doesn't retroactively change
    chapter 5's stored profile. Each chapter's meta locks its character
    state; the voice transitions across chapters naturally.
    """

    sentences: list[Sentence] = Field(default_factory=list)
    characters: list[Character] = Field(default_factory=list)


class AnalyzedSentence(BaseModel):
    """Intermediate LLM output — raw sentence text + attributes, no
    positions yet. ``locate_sentences`` later maps text → (line, col).

    ``speaker`` is a free-form string from the LLM. ``core.nlp.reconcile``
    maps it to a ``character_id`` using the global ``characters.json``.
    """

    text: str
    speaker: str = ""
    tone: Tone = Tone.NEUTRAL


class ClassifiedCharacters(BaseModel):
    """LLM output for the character-classification sub-task (Phase A1
    of the per-chapter analysis pipeline, see service.py).

    Lists every non-narrator character the LLM identified in this
    chapter, split into three buckets:

    - ``new_names``: real, named characters not in the known roster
      (proper-noun / unique identifier — 萧炎, 林黛玉, 药老). Only the
      name is emitted here — the full profile is generated by a
      follow-up ``profile_new_characters`` call that gets cross-chapter
      introduction context (the reader may have jumped past the
      character's first appearance, so the current chapter alone may
      lack good descriptive material).
    - ``evolved``: known characters whose profile materially changed
      in this chapter (full new profile emitted directly).
    - ``incidentals``: descriptor-named one-off speakers in this
      chapter only (妇人, 男子, 仆人, 婢女 — generic role labels, not
      proper nouns). Full profile emitted inline since they're
      single-chapter and cross-chapter context wouldn't help. Service
      layer assigns a chapter-local **negative** ``id`` and stores them
      ONLY in the chapter snapshot — they never enter
      ``characters.json``. Identification anywhere in the system uses
      ``id < 0``, never name parsing — the LLM-given descriptor stays
      on as the user-facing ``name``.

    Known characters with no meaningful change are absent (LLM is
    instructed not to emit them).
    """

    new_names: list[str] = Field(default_factory=list)
    evolved: list[Character] = Field(default_factory=list)
    incidentals: list[Character] = Field(default_factory=list)


class ChapterDetection(BaseModel):
    """LLM-side output for TXT chapter structure inference (§2.4.1).

    Two disjoint modes depending on ``has_toc``. Pydantic doesn't force the
    branches to be mutually exclusive — callers must inspect ``has_toc``
    before reading the corresponding fields.
    """

    has_toc: bool = False
    # Populated when has_toc=True — the ordered list of chapter titles
    # extracted from the table of contents block at this batch's window.
    chapter_titles: list[str] = Field(default_factory=list)
    # TOC-mode pagination signal. ``False`` means the LLM has not yet reached
    # the end of the TOC in the current batch and the caller should feed the
    # next 200-line batch with the accumulated titles as a hint. Always
    # ``True`` for non-TOC (pattern) mode — pagination only applies to TOC.
    toc_complete: bool = True
    # Populated when has_toc=False — preface sections preceding chapter 1
    # (e.g. 楔子, 序章). Empty if there is no preface.
    preface_titles: list[str] = Field(default_factory=list)
    # Populated when has_toc=False — the title of the first real chapter.
    first_chapter_title: str = ""
    # Populated when has_toc=False — a Python regex (anchored to line start)
    # that matches subsequent chapter headings of the same form.
    chapter_pattern: str = ""


class Speaker(BaseModel):
    """A voice available on the TTS backend, tagged with the same attribute
    vocabulary as book characters so one can be matched against the other.
    """

    speaker_id: str
    gender: Gender = Gender.NEUTRAL
    age: Age = Age.ADULT
    personality: list[Personality] = Field(default_factory=list)
    source: str = ""  # e.g. "volcengine-seed-tts-2.0"
    notes: str = ""


# --- API DTOs ---

class BookListItem(BaseModel):
    book_id: str
    title: str
    author: str
    status: BookStatus
    chapter_count: int


class BookListResponse(BaseModel):
    books: list[BookListItem]


class UploadResponse(BaseModel):
    book_id: str
    status: BookStatus
    title: str
    chapter_count: int


class CharacterUpdate(BaseModel):
    """Partial update payload for ``PATCH
    /api/books/{book_id}/characters/{character_id}``.

    All fields optional — the server only overwrites keys the client
    actually sent. Identity / name aren't editable here: the LLM uses
    them to recognise the character across chapters, so a user rename
    would break re-analysis. Voice selection is driven by the matcher
    inputs (gender / age / personality), so those are the editable
    fields.
    """

    gender: Gender | None = None
    age: Age | None = None
    personality: list[Personality] | None = None


class TTSRequest(BaseModel):
    """Request a sentence's TTS audio.

    The voice is resolved server-side: narrator ids 0..15 map to
    pre-defined voices (configured in ``app.core.narrator``); ids ≥ 16
    are book characters whose attributes are looked up in the book's
    ``characters.json``.

    ``speed`` is intentionally absent — playback speed is applied
    client-side via ``AVAudioUnitTimePitch`` at play time so a single
    cached audio file serves all speeds.
    """

    book_id: str
    chapter_id: int
    character_id: int
    text: str
    tone: Tone = Tone.NEUTRAL
